"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import type { Listing } from "@/lib/types";
import { DEFAULT_LISTING_IMAGE } from "@/lib/default-listing-image";
import { isAutoGeneratedVideoThumbnail } from "@/lib/parse-video-url";
import { PropertyVideo } from "@/components/PropertyVideo";

export function PropertyGallery({
  listing,
  openFirstImage = false,
}: {
  listing: Listing;
  openFirstImage?: boolean;
}) {
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null);
  const videoUrl = listing.videoUrl?.trim() ?? "";
  let galleryImages =
    listing.images?.length > 0 ? listing.images : videoUrl ? [] : [DEFAULT_LISTING_IMAGE];
  if (videoUrl && galleryImages.length > 0) {
    galleryImages = galleryImages.filter((src) => !isAutoGeneratedVideoThumbnail(src));
  }
  const images =
    galleryImages.length > 0
      ? galleryImages
      : videoUrl
        ? []
        : [DEFAULT_LISTING_IMAGE];

  useEffect(() => {
    if (openFirstImage && images.length > 0) setLightboxIndex(0);
  }, [openFirstImage, images.length]);

  return (
    <>
      <div className="space-y-3 overflow-hidden rounded-xl">
        {videoUrl ? (
          <div className="overflow-hidden rounded-lg border border-sand-200 bg-sand-50 shadow-sm">
            <PropertyVideo videoUrl={videoUrl} title={listing.title} />
          </div>
        ) : null}
        {images.map((src, i) => (
          <button
            key={i}
            type="button"
            className="relative block aspect-[16/10] w-full overflow-hidden rounded-lg bg-sand-100 text-left"
            onClick={() => setLightboxIndex(i)}
          >
            <Image
              src={src}
              alt={`${listing.title} – image ${i + 1}`}
              fill
              className="object-cover transition hover:opacity-95"
              sizes="(max-width: 1024px) 100vw, 66vw"
              priority={i === 0}
            />
          </button>
        ))}
      </div>

      {lightboxIndex !== null && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 p-4"
          onClick={() => setLightboxIndex(null)}
          role="dialog"
          aria-modal="true"
          aria-label="Image lightbox"
        >
          <button
            type="button"
            onClick={() => setLightboxIndex(null)}
            className="absolute right-4 top-4 rounded-full bg-white/20 p-2 text-white hover:bg-white/30"
            aria-label="Close"
          >
            <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
          <div className="relative max-h-[90vh] max-w-5xl" onClick={(e) => e.stopPropagation()}>
            <Image
              src={images[lightboxIndex]}
              alt={`${listing.title} – image ${lightboxIndex + 1}`}
              width={1200}
              height={800}
              className="max-h-[90vh] w-auto rounded-lg object-contain"
              unoptimized={images[lightboxIndex]?.startsWith("data:") || images[lightboxIndex]?.startsWith("blob:")}
            />
          </div>
        </div>
      )}
    </>
  );
}
