"use client";

import { useState, useCallback } from "react";
import Image from "next/image";
import Link from "next/link";
import type { Listing } from "@/lib/types";
import { DEFAULT_LISTING_IMAGE } from "@/lib/default-listing-image";
import { isAutoGeneratedVideoThumbnail } from "@/lib/parse-video-url";
import { CardVideoPreview } from "./CardVideoPreview";
import { ListingFeatureChips } from "./ListingFeatureChips";
import { listingHasFeatureChips } from "@/lib/listing-feature-labels";

function formatPrice(price: number, currency: string) {
  if (!price || price <= 0) return "Price on request";
  if (currency === "USD") return `$${price.toLocaleString()}`;
  return `${price.toLocaleString()} ${currency}`;
}

const SWIPE_THRESHOLD = 50;

export function PropertyCard({ listing }: { listing: Listing }) {
  const hasVideo = Boolean(listing.videoUrl?.trim());
  let images =
    listing.images?.length > 0
      ? listing.images
      : hasVideo
        ? []
        : [DEFAULT_LISTING_IMAGE];
  if (hasVideo) {
    images = images.filter((src) => !isAutoGeneratedVideoThumbnail(src));
  }
  if (images.length === 0 && !hasVideo) {
    images = [DEFAULT_LISTING_IMAGE];
  }
  const [currentIndex, setCurrentIndex] = useState(0);
  const [touchStartX, setTouchStartX] = useState<number | null>(null);

  const goPrev = useCallback(
    (e: React.MouseEvent | React.TouchEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setCurrentIndex((i) => (i <= 0 ? images.length - 1 : i - 1));
    },
    [images.length]
  );

  const goNext = useCallback(
    (e: React.MouseEvent | React.TouchEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setCurrentIndex((i) => (i >= images.length - 1 ? 0 : i + 1));
    },
    [images.length]
  );

  const onTouchStart = useCallback((e: React.TouchEvent) => {
    setTouchStartX(e.targetTouches[0].clientX);
  }, []);

  const onTouchEnd = useCallback(
    (e: React.TouchEvent) => {
      if (touchStartX == null) return;
      const endX = e.changedTouches[0].clientX;
      const delta = touchStartX - endX;
      if (delta > SWIPE_THRESHOLD) setCurrentIndex((i) => (i >= images.length - 1 ? 0 : i + 1));
      else if (delta < -SWIPE_THRESHOLD) setCurrentIndex((i) => (i <= 0 ? images.length - 1 : i - 1));
      setTouchStartX(null);
    },
    [touchStartX, images.length]
  );

  const showArrows = images.length > 1;
  const currentImage = images[currentIndex] ?? images[0];
  const videoOnly = images.length === 0 && hasVideo;

  return (
    <article className="group overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm transition hover:shadow-lg hover:border-sand-300">
      <Link href={`/properties/${listing.slug}`} className="block">
        <div
          className="relative aspect-[4/3] overflow-hidden bg-sand-100 touch-pan-y"
          onTouchStart={videoOnly ? undefined : onTouchStart}
          onTouchEnd={videoOnly ? undefined : onTouchEnd}
        >
          {videoOnly ? (
            <>
              <CardVideoPreview videoUrl={listing.videoUrl!} title={listing.title} />
              <span
                className="pointer-events-none absolute inset-0 flex items-center justify-center"
                aria-hidden
              >
                <span className="flex h-14 w-14 items-center justify-center rounded-full bg-black/50 text-white shadow-lg ring-2 ring-white/30 transition group-hover:bg-black/60">
                  <svg className="h-7 w-7" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8 5v14l11-7-11-7z" />
                  </svg>
                </span>
              </span>
            </>
          ) : (
            <Image
              src={currentImage}
              alt={`${listing.title} – image ${currentIndex + 1}`}
              fill
              className="object-cover transition duration-300 group-hover:scale-[1.03]"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
            />
          )}
          {showArrows && (
            <>
              <button
                type="button"
                onClick={goPrev}
                className="absolute left-2 top-1/2 z-10 flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full bg-white/90 text-sand-800 shadow-md hover:bg-white focus:outline-none focus:ring-2 focus:ring-brand-500"
                aria-label="Previous image"
              >
                <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
              </button>
              <button
                type="button"
                onClick={goNext}
                className="absolute right-2 top-1/2 z-10 flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full bg-white/90 text-sand-800 shadow-md hover:bg-white focus:outline-none focus:ring-2 focus:ring-brand-500"
                aria-label="Next image"
              >
                <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </button>
            </>
          )}
          {listing.featured && (
            <span className="absolute left-3 top-3 z-10 rounded-full bg-brand-600 px-2.5 py-0.5 text-xs font-medium text-white shadow">
              Featured
            </span>
          )}
          <span className="absolute right-3 top-3 z-10 rounded-lg bg-white/95 px-2.5 py-1 text-xs font-medium text-sand-700 capitalize shadow-sm">
            {listing.propertyType}
          </span>
          {hasVideo && (
            <span className="absolute bottom-3 left-3 z-10 inline-flex items-center gap-1 rounded-full bg-black/65 px-2 py-1 text-xs font-medium text-white shadow-sm">
              <svg className="h-3.5 w-3.5 shrink-0" fill="currentColor" viewBox="0 0 24 24" aria-hidden>
                <path d="M8 5v14l11-7-11-7z" />
              </svg>
              Video
            </span>
          )}
          {showArrows && (
            <span className="absolute bottom-2 left-1/2 z-10 -translate-x-1/2 rounded-full bg-black/50 px-2 py-0.5 text-xs text-white">
              {currentIndex + 1} / {images.length}
            </span>
          )}
        </div>
        <div className="p-4">
          <p className="text-sm font-medium text-brand-600">{listing.location}</p>
          <h2
            className="mt-1 line-clamp-4 break-words font-semibold text-sand-900 group-hover:text-brand-600 transition-colors"
            title={listing.title}
          >
            {listing.title}
          </h2>
          <p className="mt-2 text-lg font-semibold text-sand-900">
            {formatPrice(listing.price, listing.currency)}
          </p>
          {listing.area && (
            <p className="mt-1 text-sm text-sand-600">{listing.area}</p>
          )}
          {listingHasFeatureChips(listing) && (
            <div className="mt-2">
              <ListingFeatureChips listing={listing} max={8} />
            </div>
          )}
        </div>
      </Link>
    </article>
  );
}
