/**
 * Extract YouTube video id from common URL shapes (watch, youtu.be, Shorts, embed, mobile).
 */
export function getYouTubeId(url: string): string | null {
  const u = url.trim();
  if (!u) return null;

  let m = u.match(/youtu\.be\/([a-zA-Z0-9_-]{11})/);
  if (m) return m[1];

  m = u.match(/youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/);
  if (m) return m[1];

  m = u.match(/youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/);
  if (m) return m[1];

  m = u.match(/(?:youtube\.com\/watch\?v=|m\.youtube\.com\/watch\?v=)([a-zA-Z0-9_-]{11})/);
  if (m) return m[1];

  if (/youtube\.com|youtu\.be/i.test(u)) {
    m = u.match(/[?&]v=([a-zA-Z0-9_-]{11})/);
    if (m) return m[1];
  }

  return null;
}

export function getVimeoId(url: string): string | null {
  const m = url.trim().match(/vimeo\.com\/(?:video\/)?(\d+)/);
  return m ? m[1] : null;
}

export function isDirectVideoFileUrl(url: string): boolean {
  const u = url.trim();
  if (!u) return false;
  if (/\.(mp4|webm|ogg|mov)(\?|#|$)/i.test(u)) return true;
  // Cloudinary video URLs often look like:
  // https://res.cloudinary.com/<cloud>/video/upload/v.../<public_id>
  return /res\.cloudinary\.com\/.+\/video\/upload\//i.test(u);
}

/**
 * Auto-generated YouTube / Vimeo poster URLs — often solid black/grey in the grid; skip when a real video player is shown.
 */
export function isAutoGeneratedVideoThumbnail(url: string): boolean {
  const u = url.trim();
  return (
    /img\.youtube\.com\/vi\//i.test(u) ||
    /i\.ytimg\.com\/vi\//i.test(u) ||
    /vumbnail\.com/i.test(u)
  );
}
